framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
#        app: cache.adapter.apcu
#        app: cache.adapter.doctrine
#         app: cache.adapter.system
#         app: cache.adapter.filesystem
#         app: cache.adapter.psr6
#         app: cache.adapter.redis
#         app: cache.adapter.memcached


